import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./../globals.css";
import Providers from "../providers";
// import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          {/* <ToastContainer /> */}
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
