import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./../globals.css";
import Providers from "../providers";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Harmony Bookme",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/bookme-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </head>
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <div>{children}</div>
          <Toaster
            position="top-right"
            toastOptions={{ className: "custom-success-toast" }}
          />
        </Providers>
      </body>
    </html>
  );
}